### ISSUE TITLE
Security token invalid when executing script to create role for Grafana

### ISSUE THREAD

**Issue by CrazyShipOne** [aws-samples/aws-iot-twinmaker-samples#23]
Hi,

When I execute the script

`python3 $GETTING_STARTED_DIR/src/modules/grafana/create_grafana_dashboard_role.py --workspace-id $WORKSPACE_ID --region $AWS_DEFAULT_REGION --profile $MyProfile`

It produces error _**botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the GetCallerIdentity operation: The security token included in the request is invalid**_.

This happens when using a specific profile.

**Comment by johnnyw-aws** [comment]
Thanks for your contribution!
