### ISSUE TITLE
Grafana not showing data

### ISSUE THREAD

**Issue by CrazyShipOne** [aws-samples/aws-iot-twinmaker-samples#25]
Hi,

I executed all scripts, everything seems fine. However I stucked at the last step after import dashboard to Grafana, there is no data in every tab:
![image](https://user-images.githubusercontent.com/19662816/153370129-9cd57fcf-95a5-44f1-9690-9c07a95a9389.png)

It there any step should be done?

Thanks.

**Comment by johnnyw-aws** [comment]
Hi,

First just want to confirm the following:

* the "Save & Test" to the workspace in the data source step was successful
* the `get-property-value-history` step in the README returns results
* the grafana plugin steps in [grafana_local_docker_setup](https://github.com/aws-samples/aws-iot-twinmaker-samples/blob/main/docs/grafana_local_docker_setup.md) were successful

If so, then can you check whether there are any errors in the browser developer console? The "Unknown query type" error suggests to me there may have been an issue in setup/config of the plugin. Another alternative is to try to rerun the setup using the Cloud9 instructions to see if it could be a local issue

Thanks

**Comment by CrazyShipOne** [comment]
Hi @johnnyw-aws,

- the "Save & Test" to the workspace in the data source step was successful
_Every script in the 'Deploying the Sample Cookie Factory Workspace' runs successfully, except uploading mkv files went wrong will ssl related exception, but it seems like the last thing the script does, so it is not a big deal?_
- the get-property-value-history step in the README returns results
_It returns like 
`{
    "propertyValues": [
        {
            "entityPropertyReference": {
                "componentName": "AlarmComponent",
                "entityId": "Mixer_2_06ac63c4-d68d-4723-891a-8e758f8456ef",
                "externalIdProperty": {
                    "alarm_key": "Mixer_2_23a4ba92-f85c-423a-ba95-0a2f392d68eb"
                },
                "propertyName": "alarm_status"
            },
            "values": [
                {
                    "timestamp": "2022-02-10T15:34:54+08:00",
                    "value": {
                        "stringValue": "NORMAL"
                    }
                }
            ]
        }
    ]
}`_
- the grafana plugin steps in [grafana_local_docker_setup](https://github.com/aws-samples/aws-iot-twinmaker-samples/blob/main/docs/grafana_local_docker_setup.md) were successful
_I'm using AWS Grafana, just thought data source are already there...The unknown query type is caused by no data source created... But after I create twinMaker data source and reimport dashboard, only alarm list tab shows data:
![image](https://user-images.githubusercontent.com/19662816/153530181-814f1c69-baaf-4d2b-a3ec-00dab75726e3.png)
I also checked config for alarm history tab and find value of Entity is **${sel_entity}=**
![image](https://user-images.githubusercontent.com/19662816/153530306-0ea77f71-0fb3-43bc-b2e2-6e467916b71b.png)_
_Does that means I need to put entity id for each query?_

Thanks.

**Comment by CrazyShipOne** [comment]
Just figured out it needs to click an item in Alarm List tab...Now everything works fine.

Thanks for helping!
