### ISSUE TITLE
AttributeError: module 'deploy_utils' has no attribute 'WorkspaceUtils'

### ISSUE THREAD

**Issue by bluesatheesh** [aws-samples/aws-iot-twinmaker-samples#35]
python3 $GETTING_STARTED_DIR/src/modules/grafana/cleanup_grafana_dashboard_role.py --workspace-id $WORKSPACE_ID --region $AWS_DEFAULT_REGION
Traceback (most recent call last):
  File "/home/ubuntu/environment/aws-iot-twinmaker-samples/src/modules/grafana/cleanup_grafana_dashboard_role.py", line 80, in <module>
    main()
  File "/home/ubuntu/environment/aws-iot-twinmaker-samples/src/modules/grafana/cleanup_grafana_dashboard_role.py", line 44, in main
    ws = deploy_utils.WorkspaceUtils(
AttributeError: module 'deploy_utils' has no attribute 'WorkspaceUtils'

**Comment by MaxZyantao** [comment]
Hi @bluesatheesh , I just tried the command and worked fine for me. Also the `WorkspaceUtils` does exist. Could you please pull the latest changes and try again? Thanks.

```
aws-iot-twinmaker-samples % python3 $GETTING_STARTED_DIR/src/modules/grafana/cleanup_grafana_dashboard_role.py --workspace-id $WORKSPACE_ID --region $AWS_DEFAULT_REGION

No dashboard role to delete was found for workspace CookieFactory.
```

**Comment by bluesatheesh** [comment]
@MaxZyantao I've fixed the issue. This is due to the python and pip. Need to use python 3.8 and above

**Comment by bluesatheesh** [comment]
I've deployed the cookie factory and its working perfect.

**Comment by MaxZyantao** [comment]
Perfect! I'll close this issue!
