### ISSUE TITLE
Graphic with incorrect service name capitalization

### ISSUE THREAD

**Issue by gadams999** [aws-samples/aws-iot-twinmaker-samples#44]
Minor issue, the image from [this link](https://github.com/aws-samples/aws-iot-twinmaker-samples/tree/main/src/modules/sitewise) has `Twinmaker` and `Sitewise` instead of `TwinMaker` / `SiteWise`.

**Comment by johnnyw-aws** [comment]
Thanks for raising this, we've updated the image with this PR: https://github.com/aws-samples/aws-iot-twinmaker-samples/pull/47
