### ISSUE TITLE
Error in running CDK deploy

### ISSUE THREAD

**Issue by koushikpuppala** [aws-samples/aws-iot-twinmaker-samples#92]
![image](https://user-images.githubusercontent.com/70138027/219601848-91053dd2-274e-49d8-839b-ea2631d6b4ea.png)

**Comment by stevenyang-aws** [comment]
Hi @koushikpuppala , could you elaborate a bit more on the details? Which step is failing for you?

**Comment by koushikpuppala** [comment]
I found alternative. Thanks you.
